### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by aliglelo** [prasathmani/help-docs#1]
Hello sir i am student having passion of web developement currently i am designing a website 
But I am still new in this field and i need a login system using php without a database as you have used in tinny file manager.
please sir cuold you write me a php code same as login for tiny file manager which on successful login redirects to my html home page?
please sir @prasathmani  help me.
Thanks!

**Comment by prasathmani** [comment]
@aliglelo try the sample login, https://file.io/O8GiTX

**Comment by aliglelo** [comment]
Thanks for considring my request but something is wrong with the link your provided sir
because on opening it says "file.io
404
Page not found"
Please help me out sir!
Thanks.
![screenshot from 2018-12-19 16-33-25](https://user-images.githubusercontent.com/30858084/50217727-5b720200-03ab-11e9-9858-1b476044ee30.png)

**Comment by prasathmani** [comment]
[try this](https://tinyfilemanager.eu-gb.mybluemix.net/Login.zip)

**Comment by aliglelo** [comment]
I tried it and it worked smoothly 
Thanks alot sir for your giuidance!

**Comment by prasathmani** [comment]
try free login form designs https://colorlib.com/wp/html5-and-css3-login-forms/ or you can use [Bootstrap](https://getbootstrap.com/)

**Comment by aliglelo** [comment]
Thanks alot sir!

**Comment by aliglelo** [comment]
Hello sir!
I want a help sir...
I am self taught web developing enthusiast and I want to use your "[tiny file manager](https://github.com/prasathmani/tinyfilemanager) Project for my own Forum....
so can you plz do me a favour of removing branding of Tinyfilamanger from project  in a seperete file so i can use it for my own forum
I will definately credit you in the forum...
so please sir help me...
Thanks!
